# -*- restclient -*-
#
# LOGIN
POST http://localhost:8000/login/
Content-Type: application/json
{
	"username": "mariotti",
	"password": "demo"
}

# Change Face
POST http://localhost:8000/faces/0
Content-Type: application/json
Authorization: Token dbe2f2fd50d1e8d2e723f08b5b25fcd0257ddf50
