# Generated by Django 2.2.1 on 2019-05-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='togglaction',
            name='description',
        ),
        migrations.AlterField(
            model_name='togglaction',
            name='project',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='togglaction',
            name='tags',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
