# Generated by Django 2.2.1 on 2019-05-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0002_auto_20190523_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='togglcredentials',
            name='api_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
