# Generated by Django 2.2.1 on 2019-06-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0003_auto_20190525_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='togglaction',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
