# Generated by Django 2.2.1 on 2019-06-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0004_auto_20190601_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='togglaction',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
